services:
  # --- 1. NEXTCLOUD ---
  nextcloud:
    image: nextcloud:stable-apache
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    volumes:
      - nextcloud_data:/var/www/html
      - /home/athnor/transcription_pipeline/whisper/chapitres_audio:/var/www/html/data/Athnor/files/chapitres_audio
      - /home/athnor/transcription_pipeline/whisper/chapitres_ecrits:/var/www/html/data/Athnor/files/chapitres_ecrits
      - /home/athnor/transcription_pipeline/whisper/archives_audio:/var/www/html/data/Athnor/files/archives_audio
      - /home/athnor/transcription_pipeline/pipeline-gemini/Photos_a_transcrire:/var/www/html/data/Athnor/files/Photos_a_transcrire
      - /home/athnor/transcription_pipeline/pipeline-gemini/Transcriptions_photos_MD:/var/www/html/data/Athnor/files/Transcriptions_photos_MD

  # --- 2. WORKER GEMINI (VISION) ---
  # transcription-worker:
  #   build: /home/athnor/transcription_pipeline/pipeline-gemini
  #   container_name: pipeline_transcription_worker
  #   user: "33:33"
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes:
  #     - /home/athnor/transcription_pipeline/pipeline-gemini/app:/app
  #   depends_on:
  #     - nextcloud

  # --- 3. WORKER WHISPER ---
  whisper-transcriber:
    build: /home/athnor/transcription_pipeline/whisper/app
    container_name: whisper_transcriber
    network_mode: "host"
    user: "33:33"
    restart: unless-stopped
    runtime: nvidia
    environment:
      - HF_HOME=/tmp/huggingface
      - TZ=Europe/Paris
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /home/athnor/transcription_pipeline/whisper/app:/app
      - /home/athnor/transcription_pipeline/whisper/chapitres_audio:/data/chapitres_audio
      - /home/athnor/transcription_pipeline/whisper/chapitres_ecrits:/data/chapitres_ecrits
      - /home/athnor/transcription_pipeline/whisper/archives_audio:/data/archives_audio
      - whisper_model_cache:/tmp/huggingface
    depends_on:
      - nextcloud

volumes:
  whisper_model_cache:
  nextcloud_data:
    external: true
    name: nextcloud-server_data
